{{- if and .Values.sysdig.accessKey (not .Values.sysdig.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sysdig.fullname" . }}
  labels:
    app: {{ template "sysdig.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
 access-key : {{ required "A valid .Values.sysdig.accessKey is required" .Values.sysdig.accessKey | b64enc | quote }}
{{- end }}
